version: "3.8"
services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    networks:
      - lesson
networks:
  lesson: